clean: true
author: Joshua Emmons
author_url: https://uptake.com
github_url: https://github.com/UptakeMobile/uptake-auth-ios
module: UptakeAuth
root_url: http://mobile-toolkit-docs.services.common.int.uptake.com/docs/uptake-auth-ios/

# custom_categories:
#   - name: Helpers
#     children:
#     - ErrorHelper
#   - name: Factories
#     children: 
#     - Logging
    
